### PR TITLE
My hacks

### PR DESCRIPTION
**Pull request by ndw**
I rewrote most of it :-)

### CODE REVIEW

**Comment by DALDEI** [comment]
Accepting merge.
May rework use of supervisord

**Comment by ndw** [comment]
Yeah. I know you're not fond of it, but it seems to be a pretty common idiom in the Docker world.

**Comment by DALDEI** [comment]
What is the purpose of MarkLogic.rpm in builder ?  (getml is run which copies MarkLogic.rpm to the docker daemon -- but doesnt appear to do anything with it -- is this just leftover .. ? )

Also, in coreos supervisord is configured but errors when starting with no cmd.
.e. if I run

`docker run -it coreos  
`
What is supposed to happen ? ( I nievely assumed it would run /bin/bash - but it seems to run supervisord but I cant tell what its doing)

Thanks.

(oh yea, it _works_  so far ! )

**Comment by ndw** [comment]
The getml call in builder was an oversight.

"Nothing" is supposed to happen. The supervisord process starts and managed processes and never exists. I cleaned up a few things to remove some warning messages. New PR coming shortly.

**Pull request merged**
